---
resources:
- name: helloworld
  type: git
  source:
    branch: master
    uri: https://github.com/riteshsaha/helloworld.git
- name: cf-resource
  type: cf
  source:
    api: https://api.sys.wdc-np.itcna.vmware.com
    organization: Devportal
    username: saharitesh@vmware.com
    password: VmwareDTTL007*
    skip_cert_check: true
    space: dev

jobs:
- name: unit-test
  public: true
  plan:
  - get: helloworld
    trigger: true

- name: run-helloworld-app
  public: true
  plan:
  - get: helloworld
    passed: [unit-test]
    trigger: true
  - task: helloworld-task
    config:
        platform: linux

        image_resource:
          type: docker-image
          source: {repository: busybox}

        run:
          path: echo
          args: [hello world]

- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: helloworld
    passed: [run-helloworld-app]
    trigger: true
  - put: cf-resource
    params:
      manifest: helloworld/manifest.yml