---
resources:
- name: helloworld
  type: git
  source:
    uri:    https://github.com/riteshsaha/helloworld.git
    branch: master

jobs:
- name: unit-test
  public: true
  plan:
  - get: helloworld
    trigger: true
    
- name: deploy
  public: true
  plan:
  - get: helloworld
    passed: [unit-test]
    trigger: true
  - task: helloworld-task
    config:
        platform: linux

        image_resource:
          type: docker-image
          source: {repository: busybox}

        run:
          path: echo
          args: [hello world]